server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml
  sync_period: 10s
  ignore_invalid_yaml: false

clients:
  - url: http://10.34.154.94:3100/loki/api/v1/push

scrape_configs:
- job_name: payara
  static_configs:
  - targets:
      - localhost
    labels:
      job: 
      __path__: C:\payara5\glassfish\domains\demo-project\logs\server.log
