---
- name: Install JAVA
  hosts: utilities
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: add apt source
      ansible.builtin.shell: |
        wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/adoptium.gpg > /dev/null
        echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | sudo tee /etc/apt/sources.list.d/adoptium.list
        sudo apt update
      become: true

    - name: Install JAVA 8
      ansible.builtin.apt:
        name: temurin-8-jdk
        state: present
      become: true

    - name: Install JAVA 17
      ansible.builtin.apt:
        name: temurin-17-jdk
        state: present
      become: true
