---
- name: Install Necessary Dependency
  hosts: utilities
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Install Jq
      ansible.builtin.apt:
        name: jq
        state: present
      become: true

    - name: Install wget
      ansible.builtin.apt:
        name: wget
        state: present
      become: true

    - name: Install musl
      ansible.builtin.apt:
        name: musl
        state: present
      become: true
